[package]
name = "rsScrabble"
version = "0.4.0"
edition = "2021"

[lib]
name = "rsScrabble"

[dependencies.pyo3]
version = "0.15.1"
features = ["extension-module"]

[dev-dependencies]
criterion = {version = "0.3", features = ["html_reports"]}

[[bench]]
name = "anagrammer"
harness = false
