#!/usr/bin/env python
import os
import sys
import argparse

import pyScrabbleUtils.scrabbleBoard as sb


def main(args):
	if args.scrabbleStats:
		sb.computeScrabbleStats()
		sys.exit(0)

	if args.show:
		show=True
	else:
		show=False

	if args.wordCheck:
		board = sb.Board(show=show)
		print({w.asString() for w in board.players.wordTree.getAllAnagrams(args.wordCheck)})
		sys.exit(0)

	if args.players:
		nPlayers = args.players
	else:
		nPlayers = 1

	if args.auto:
		board = sb.Board(nPlayers=nPlayers, show=show)
		board.startAutomaton()
		sys.exit(0)

	else:
		board = sb.Board(show=True)
		board.startAdviser()


if __name__=="__main__":
	parser = argparse.ArgumentParser(description="Automatons to play scrabble")
	parser.add_argument('-w','--wordCheck', type=str, help="returns all words formed with these letters")
	parser.add_argument('-p','--players', type=int, help="number of players")
	parser.add_argument('--scrabbleStats', action='store_true', help="makes stats about probability of having a scrabble")
	parser.add_argument('-a','--auto', action='store_true', help="launches a game with automatic players")
	parser.add_argument('-s','--show', action='store_true', help="shows current best word")
	args = parser.parse_args()
	main(args)